export * from './CategoriaRegistro'
export * from './MarcaRegistro';
export * from './ProductoRegistro';
export * from './SalidaRegistro';
export * from './EntradaRegistro';
export * from './AreaRegistro';
export * from './EntradaProductoRegistro';
export * from './ProductoSalidaRegistro';
export * from './InicioSesionPage';
export * from './UsuarioRegistro';